### PR TITLE
Handle historical Object GenericTypeAnnotation

### PR DESCRIPTION
**Pull request by gomesalexandre**
#185

### CODE REVIEW

**Comment by gomesalexandre** [comment]
[clabot:check]

**Review by aminya — APPROVED** [review]

**Comment by k4b7** [comment]
@gomesalexandre thanks for signing the CLA.  We had to disable the bot for a while so I'll be standing in until we can revive it.

**Comment by k4b7** [comment]
This does change the semantics when converting between flow and typescript since flow treats `Object` and `Function` as `any`.  I'm curious why the output uses `{[key: string]: any}` instead of TypeScript's `object` type.  Is there a difference between the two?

**Comment by gomesalexandre** [comment]
> I'm curious why the output uses `{[key: string]: any}` instead of TypeScript's `object` type. Is there a difference between the two?

I would rather not use `object` type. To quote [TS 2.2 release post](https://devblogs.microsoft.com/typescript/announcing-typescript-2-2/#:~:text=The%20object%20type%20is%20a,using%20strictNullChecks%20%2C%20null%20and%20undefined%20.):
```
The object type is a new type in 2.2 that matches any types except for primitive types. In other words, you can assign anything to the object type except for string, boolean, number, symbol, and, when using strictNullChecks, null and undefined.
```

It's good for pure internal methods as it defines an object in its purest sense, `a non primitive type`. But it will fail in pretty much all real-life cases:

[TS Playground Demo
](https://www.typescriptlang.org/play?#code/PQKgBAUAggzmDuBTMBjAhgOzDRiA0YABgPYBGAVoigC6FgC2xAJogDZxpgDmiGiATgEsUYMpRoQAktQTEMAchkAzNINYIAFrzBoYMQVz5Mw1Yjqxiq1CACEArjMEz4cxd0EA3ZHY4YAniZ+AA6IALQoWigA1oIYXGBKxPxgTmCITlr8AHRgklgqNASp8GrqKmopSgjI1PwBpmlZ8RChYFBMTMAAsg5o1IjAAEqIjF46YEH8xCH81PVmxHbJlhKtUCgoiHqiFFYTUzNzYD6x8enUmSZaYEzEMklgpPxo0YjUcDB+GNRoAB4QIGAEAgrDejwAXDtxDIALxgADeiWIkPkpDQ-HkAF8ICg5DBiKCsqxiFwABSkLJIgCUYGAwASqnYBFIDmwGkWrCYCmoBCQbI5xlIyDQpFBJjML02204k2mAjmEApaAACgcwHD5CqDvJafTykzHqyYOy7JzubzkMaBY9haKahKOmA+PB9nLZoItoqANqa1XTeQAXXVYF92t1DLUMGZRpNZsUFv5psFtrFDTQjudrsOHpgEBYoP6j0pxDMdIjBpZMitSfN1UTnJtOjt4pubDeNWuSKz8r8OLxjhgNgA8rsaMGKbiMDBanYaA8YQuwCPoQBucNDgDSBBWjgwmSccHob3ZTDgSim9CXo+oWVlpjmIWBBZ0kPhXqiiD8kOnQjiAchmB+JiwaIiWKJohiwFlpukCTvihLEmSaDFsQNLQRuEDIVq0zBqG-rrhhaA+thQSBrhJE6uhmFZCR5F+qRBF9lOA5QMuexwshcEznOyQLnCbFjuh27Xike4CAeDDHswZ4Xle0K3lM97BIgQA)

```js
/* 
As we can see, `object` models a generic object
It won't fail when assigned to an object
But it won't give us any type-checking for it either. In fact, it will fail if we try to e.g 
- Add/Mutate/Remove a property to our object
- Access object property using either the dot or brackets syntax
*/

let b: object = {foo: 'bar'}
console.log(b.foo) // fails, but shouldn't, we should be able to access a property
b.aProp = 'aProp' // fails, but shouldn't, we should be able to add new properties
b['aProp'] = 'aProp' // fails, but shouldn't, we should be able to add new properties
delete b.foo // fails, but shouldn't, we should be able to delete the foo property
const isBObject = b.constructor === Object; // OK, object inherits methods from Object.prototype

let a: {[key: string]: any} = {foo: 'bar'} // OK 
console.log(a.foo) // OK
a.aProp = 'aProp' // OK
a['aProp'] = 'aProp' // OK
a.aProp = 'aProp' // OK
const isAObject = a.constructor === Object // OK, object inherits methods from Object.prototype
```

**Review by k4b7 — APPROVED** [review]
LGTM.  Thanks for adding this functionality.

**Pull request merged**
