### PR TITLE
Read prettier config file if exists to determine prettier options 

### LINKED ISSUE #78: read .prettierrc if exists to determine prettier options

### PR DESCRIPTION
**Pull request by spiroka**
closes #78

### CODE REVIEW

**Comment by spiroka** [comment]
cli.js now creates a new commander.Command instance for every run instead of using the default instance. This was necessary because options are cached which made some unit tests fail by options being carried over from previous tests.

**Review by k4b7 — CHANGES_REQUESTED** [review]
Thanks for adding this feature and for the awesome tests.  This change appears to break permalinks in the playground.  It just loads the page with all of the defaults. That'll need to be fixed before this can be merged.

**Comment by spiroka** [comment]
Found the problem. Should work now.

**Review by aminya — APPROVED** [review]
This is very nice! It will decrease the git diff, and so it will be easier to review the changes!

**Review by k4b7 — APPROVED** [review]
LGTM.  Thanks for fixing the permalink issue.

**Pull request merged**
