### PR TITLE
Handle historical Function GenericTypeAnnotation

### PR DESCRIPTION
**Pull request by gomesalexandre**
#185

### CODE REVIEW

**Comment by gomesalexandre** [comment]
[clabot:check]

**Review by aminya — APPROVED** [review]

**Comment by k4b7** [comment]
Flow treats the type `Function` as `any` so this changes the semantics a bit when converting.  It's a change for the better but it will require people fix problems if they exists.  I'm curious why you went to `(...args: Array<any>) => any` instead of `Function` in TypeScript.  They seem equivalent.

**Comment by gomesalexandre** [comment]
From a pure semantics standpoint, this is indeed different than its flow counterpart. 
But from a user expectations standpoint, having the historical `Function` as `any` is problematic in flow (that wasn't the original intent of this generic type annotation). 
As you've noted, this is a change for the better to go off the 1/1 conversion route here. 

Regarding your second point, it is the exact same but provides more incentive to fix IMO:
- It is exactly the same as the `Function type` from a typing standpoint
- It gives a boilerplate of sorts to write the function type, so visual incentive
- If the developer uses `typescript-eslint`, the recommended configuration ships with `no-explicit-any`, which will warn them of this. Which it wouldn't with the `Function` type.

**Comment by k4b7** [comment]
Thanks for sharing your rationale.  The reasons you give are all very strong.

**Review by k4b7 — APPROVED** [review]
LGTM.  Thanks for adding this.

**Comment by gomesalexandre** [comment]
> LGTM. Thanks for adding this.

You're welcome! I've just rebased ✅

**Pull request merged**
