### PR TITLE
Add `undefined` to the maybe types.

### PR DESCRIPTION
**Pull request by davidmh**
Solves #105

### CODE REVIEW

**Comment by k4b7** [comment]
I'm not sure why the circleci build isn't working.  I'm going to try switching this over to use Github Actions this weekend.

**Comment by k4b7** [comment]
[clabot:check]

**Comment by davidmh** [comment]
[clabot:check]

**Review by k4b7 — APPROVED** [review]
LGTM.  Thanks for the PR.

**Comment by k4b7** [comment]
Not sure why the tests are being triggered.  It seems to be working with new PRs though.

**Pull request merged**
