### PR TITLE
[WIP] Handle strict, strict-local and other comment forms

### LINKED ISSUE #123: Doesn't remove "@flow strict" and "@flow strict-local" pragmas
Given these three files:

```js
// @flow
null;
```

```js
// @flow strict-local
null;
```

```js
// @flow strict
null;
```

The expected behavior is for all three ported files to become:
```js
null;
```

All three are correctly renamed to `.ts` and translated, but only the first file has its first line removed.

I assume this is a trivial fix! Tweak [this logic](https://github.com/Khan/flow-to-ts/blob/7438d9f983ecbe6964c4c7365a268fe0e79076c5/src/transform.js#L116-L128)? I could take a crack at it.

P.S. at the same time, if it's easy, it would be great to actually delete the line rather than blank it out (i.e. don't leave a blank line).

### PR DESCRIPTION
**Pull request by joebowbeer**
Added some fixtures for #123 

However, the attempted fix is overly broad and may remove useful comment text.

See failing test flow07

### CODE REVIEW

**Review by k4b7 — COMMENTED** [review]
Thanks for the PR.  It looks like one of the new fixture tests isn't passing.

**Comment by joebowbeer** [comment]
As noted in description, I added the failing test to highlight the flaw I discovered in my fix.

[WIP] abbreviates work in progress

**Comment by skovhus** [comment]
@joebowbeer anything I can do to help land this PR?

**Comment by joebowbeer** [comment]
@skovhus feel free to take this on. I made a stab at it, but as you can see my PR is not adequate.

**Comment by k4b7** [comment]
@skovhus I assigned you and then thought that was a bit too presumptuous of me.  Any help though would be greatly appreciated. 🙂

**Comment by k4b7** [comment]
Superseded by #241.

**Pull request closed without merging**
